<?php /** @var \JustShout\Gfs\Block\Html\Head $block */ ?>

<script>
    var gfsGoogleMapsApiKey = '<?= $block->getMapApiKey() ?>';
    var gfsData = {
        'accessToken': '<?= $block->getAccessToken() ?>',
        'currency_symbol': '<?= $block->getCurrencySymbol() ?>',
        'delivery_types': '<?= $block->getDeliveryTypes() ?>',
        'standard_delivery_title': '<?= $block->getStandardDeliveryTitle() ?>',
        'calendar_delivery_title': '<?= $block->getCalendarDeliveryTitle() ?>',
        'drop_point_title': '<?= $block->getDropPointTitle() ?>',
        'service_sort_order': '<?= $block->getServiceSortOrder() ?>',
        'home_icon': '<?= $block->getMapHomeIcon() ?>',
        'use_standard': '<?= $block->getUseStandard() ?>',
        'use_drop_points': '<?= $block->getUseDropPoints() ?>',
        'default_service': '<?= $block->getDefaultService() ?>',
        'default_carrier': '<?= $block->getDefaultCarrier() ?>',
        'default_carrier_code': '<?= $block->getDefaultCarrierCode() ?>',
        'default_price': '<?= $block->getDefaultPrice() ?>',
        'default_min_delivery_time': '<?= $block->getDefaultMinDeliveryTime() ?>',
        'default_max_delivery_time': '<?= $block->getDefaultMaxDeliveryTime() ?>',
        'show_calendar_no_services': '<?= $block->getShowCalendarNoService() ?>',
        'calendar_no_services': '<?= $block->getCalendarNoService() ?>',
        'day_labels': '<?= $block->getDayLabels() ?>',
        'month_labels': '<?= $block->getMonthLabels() ?>',
        'disabled_dates': '<?= $block->getDisabledDates() ?>',
        'disable_prev_days': '<?= $block->getDisabledPrevDays() ?>',
        'disable_next_days': '<?= $block->getDisabledNextDays() ?>'
    };
    var gfsLogoSrc = '<?= $block->getGfsLogoSrc() ?>';
</script>

<script id="gfs-checkout-widget-template" type="text/x-magento-template">
    <input type="hidden" name="checkoutResult" id="checkoutResult"/>
    <input type="hidden" name="sessionID" id="sessionID"/>
    <input type="hidden" name="checkoutData" id="checkoutData"/>
    <gfs-checkout
            use-standard
            <?php if ($block->getUseCalendar()): ?>use-calendar<?php endif; ?>
            <?php if ($block->getUseStores()): ?>use-droppoints<?php endif; ?>
            <?php if ($block->getUseDropPointStores()): ?>use-droppoints-stores<?php endif; ?>
            sessionid="sessionID"
            checkout-results="checkoutResult"
            checkout-data="checkoutData"
            checkout-token="<%- data.access_token %>"
            checkout-request="<%- data.gfs_data %>"
            initial-address="<%- data.initial_address %>"
            currency-symbol="<%- data.currency_symbol %>"
            delivery-types="<%- data.delivery_types %>"
            standard-delivery-title="<%- data.standard_delivery_title %>"
            calendar-delivery-title="<%- data.calendar_delivery_title %>"
            drop-point-title="<%- data.drop_point_title %>"
            service-sort-order="<%- data.service_sort_order %>"
            <?php if ($block->getMapHomeIcon()): ?>home-icon="<%- data.home_icon %>"<?php endif; ?>
            use-standard="<%- data.use_standard %>"
            use-drop-points="<%- data.use_drop_points %>"
            default-service="<%- data.default_service %>"
            default-carrier="<%- data.default_carrier %>"
            default-carrier-code="<%- data.default_carrier_code %>"
            default-price="<%- data.default_price %>"
            default-min-delivery-time="<%- data.default_min_delivery_time %>"
            default-max-delivery-time="<%- data.default_max_delivery_time %>"
            show-calendar-no-services="<%- data.show_calendar_no_services %>"
            calendar-no-services="<%- data.calendar_no_services %>"
            day-labels='<%- data.day_labels %>'
            month-labels='<%- data.month_labels %>'
            disabled-dates='<%- data.disabled_dates %>'
            disable-prev-days="<%- data.disable_prev_days %>"
            disable-next-days="<%- data.disable_next_days %>">
    </gfs-checkout>
</script>