<?php /** @var \JustShout\Gfs\Block\Html\Head $block */ ?>

<script>
    var gfsGoogleMapsApiKey = '<?= $block->getMapApiKey() ?>';
    var gfsData = {
        'accessToken': '<?= $block->getAccessToken() ?>',
        'currency_symbol': '<?= $block->getCurrencySymbol() ?>',
        'orientation': '<?= $block->getOrientation() ?>',
        'default_delivery_method': '<?= $block->getDefaultDeliveryMethod() ?>',
        'standard_delivery_title': '<?= $block->getStandardDeliveryTitle() ?>',
        'calendar_delivery_title': '<?= $block->getCalendarDeliveryTitle() ?>',
        'drop_point_delivery_title': '<?= $block->getDropPointTitle() ?>',
        'drop_point_list_button_name': '<?= $block->getDropPointListButtonName() ?>',
        'drop_point_list_button_name_unselected': '<?= $block->getDropPointListButtonNameUnselected() ?>',
        'drop_point_sort': '<?= $block->getDropPointSort() ?>',
        'service_sort_order': '<?= $block->getServiceSortOrder() ?>',
        'home_icon': '<?= $block->getMapHomeIcon() ?>',
        'store_icon': '<?= $block->getMapStoreIcon() ?>',
        'use_standard': '<?= $block->getUseStandard() ?>',
        'use_drop_points': '<?= $block->getUseDropPoints() ?>',
        'default_service': '<?= $block->getDefaultService() ?>',
        'default_carrier': '<?= $block->getDefaultCarrier() ?>',
        'default_carrier_code': '<?= $block->getDefaultCarrierCode() ?>',
        'default_price': '<?= $block->getDefaultPrice() ?>',
        'default_min_delivery_time': '<?= $block->getDefaultMinDeliveryTime() ?>',
        'default_max_delivery_time': '<?= $block->getDefaultMaxDeliveryTime() ?>',
        'show_calendar_no_services': '<?= $block->getShowCalendarNoService() ?>',
        'calendar_no_services': '<?= $block->getCalendarNoService() ?>',
        'calendar_day_prompt': '<?= $block->getCalendarDayPrompt() ?>',
        'calendar_day_non_prompt': '<?= $block->getCalendarDayNonPrompt() ?>',
        'disable_prev_days': '<?= $block->getDisabledPrevDays() ?>',
        'disable_next_days': '<?= $block->getDisabledNextDays() ?>'
    };
    var gfsLogoSrc = '<?= $block->getGfsLogoSrc() ?>';
</script>

<script id="gfs-checkout-widget-template" type="text/x-magento-template">
    <input type="hidden" name="checkoutResult" id="checkoutResult"/>
    <input type="hidden" name="sessionID" id="sessionID"/>
    <input type="hidden" name="checkoutData" id="checkoutData"/>
    <gfs-checkout
            <?php if ($block->getUseCalendar()): ?>use-calendar<?php endif; ?>
            <?php if ($block->getUseDropPointStores()): ?>use-droppoints use-droppoints-stores<?php endif; ?>
            <?php if ($block->getRequestStandard()): ?>inc-std<?php endif; ?>
            <?php if ($block->getRequestDroppoints()): ?>inc-drop-point<?php endif; ?>
            <?php if ($block->getRequestCalender()): ?>inc-day-def<?php endif; ?>
            <?php if ($block->getRequestStores()): ?>inc-stores<?php endif; ?>
            <?php if ($block->getEnableStores()): ?>enable-stores<?php endif; ?>
            sessionid="sessionID"
            checkout-results="checkoutResult"
            checkout-data="checkoutData"
            checkout-token="<%- data.access_token %>"
            checkout-request="<%- data.gfs_data %>"
            initial-address="<%- data.initial_address %>"
            currency-symbol="<%- data.currency_symbol %>"
            default-delivery-method="<%- data.default_delivery_method %>"
            orientation="<%- data.orientation %>"
            droppoint-sort-list="<%- data.drop_point_sort %>"
            standard-delivery-title="<%- data.standard_delivery_title %>"
            calendar-delivery-title="<%- data.calendar_delivery_title %>"
            drop-point-delivery-title="<%- data.drop_point_delivery_title %>"
            display-button-text="<%- data.drop_point_list_button_name %>"
            display-button-deselected-text="<%- data.drop_point_list_button_name_unselected %>"
            service-sort-order="<%- data.service_sort_order %>"
            <?php if ($block->getMapHomeIcon()): ?>home-map-icon="<%- data.home_icon %>"<?php endif; ?>
            <?php if ($block->getMapStoreIcon()): ?>store-map-icon="<%- data.store_icon %>"<?php endif; ?>
            use-standard="<%- data.use_standard %>"
            use-drop-points="<%- data.use_drop_points %>"
            default-service="<%- data.default_service %>"
            default-carrier="<%- data.default_carrier %>"
            default-carrier-code="<%- data.default_carrier_code %>"
            default-price='[<%- data.default_price %>]'
            default-min-delivery-time="<%- data.default_min_delivery_time %>"
            default-max-delivery-time="<%- data.default_max_delivery_time %>"
            show-calendar-no-services="<%- data.show_calendar_no_services %>"
            calendar-no-services="<%- data.calendar_no_services %>"
            calendar-day-prompt="<%- data.calendar_day_prompt %>"
            calendar-day-non-prompt="<%- data.calendar_day_non_prompt %>"
            <?php if ($block->getPreselectCalendarService()): ?>allow-calendar-preselect<?php endif; ?>
            disable-prev-days="<%- data.disable_prev_days %>"
            disable-next-days="<%- data.disable_next_days %>">
    </gfs-checkout>
</script>